<?php
/**
 * @file
 * Archivo para empezar a programar con Drupal
 */

/**
 * Implementa hook_menu().
 */
function saludar_menu() {
  $items['saludar/hola-mundo'] = array(
    'title' => 'Saludar',
    'page callback' => 'saludar_hola_mundo',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Callback que implementa la página: saludar/hola-mundo.
 */
function saludar_hola_mundo() {
  $variables = array(
    'message' => 'Hola Mundo',
  );
  return theme('saludar_hola_mundo', $variables);
}


/**
 * Implementa hook_theme().
 */
function saludar_theme() {
  return array(
    'saludar_hola_mundo' => array(
      'template' => 'saludar-hola-mundo',
    ),
  );
}