<?php
/*El primer hook, utilizamos el hook_help*/
function extenso_help($path, $arg){
	switch ($path){
		case "admin/help#extenso":
			return "<h1>Con ayuda de este modulo podras saber cual es el articulo mas extenso</h1>";
		break;
	}
}


function extenso_block_info(){
	$blocks['extenso'] = array(
		'info' => t('Articulo mas grande'),
		'cache' => DRUPAL_CACHE_PER_ROLE,
	);
	return $blocks;
}


function extenso_cual_es(){
	  //Obtiene la fecha
	 $hoy = getdate();
	  //Calcula la fecha de hace una semana.
	  $fecha_inicio = mktime(0, 0, 0,$hoy['mon'],($hoy['mday'] - 7), $hoy['year']);
	  //Calcula el ahora.
	  $fecha_fin = time();
	  //Utilizamos el API para obtener los posts
	   $arguments = array(':body' => 'max(body)');
	/*$query = db_select('node', 'n')
	    ->fields('n', array('nid', 'title', 'created','type'))
	    ->condition('status', 1) //Solo los publicados
	    ->condition('type', 'articulo')

	     ->condition('type', 'articulo')
	    //>where('body max',$arguments)
	    
	    ->execute();*/
	    $type='articulo';
	    $result = db_query('SELECT    n.nid, n.title, n.created, n.type
FROM node n  INNER JOIN field_data_body b on b.entity_id=n.nid WHERE n.type =:type and b.body_value=(select max(body_value) from field_data_body)  ', array(':type' => $type));


	   /* $query = db_select('node', 'n')
	    ->fields('n', array('nid', 'title', 'created'))
	    ->condition('status', 1) //Solo los pu
	    blicados
	    ->condition('created', array($fecha_inicio, $fecha_fin), 'BETWEEN')
	    ->orderBy('created', 'DESC') //Mas recientes primero
	    ->execute();*/
	  return $result;
}


function extenso_theme() {
  return array(
    'extenso-block-view' => array(
     // 'block' => array(),
      'template' => 'extenso-block-view',
    ),
  );
}


function extenso_block_view($delta = ''){
	switch ($delta){
		case 'extenso':
			$block['subject'] = t('Bloque Custom'); //La función t() permite hacer traducible la cadena
			
			if (user_access('access content')){
					$resultado = extenso_cual_es();
					$items = array();
					foreach ($resultado as $node){
						$items[] = array(
							'data' => l($node->title, 'node/' . $node->nid));
					}
					if (empty($items)){
						$block['content'] = 'No content Avaliable';
					} else {
						$block['content'] = theme('extenso-block-view', array('items' => $items));
					
					}


					/*$variables = array(
				    'block' => $block['content'],
				  );*/
					return $block;
			//return theme ('extenso_block_view',$variables);
			break;
	}
}
}